export const PROVIDER_DOT: Record<string, string> = {
  openai: 'bg-emerald-500',
  anthropic: 'bg-orange-500',
  deepseek: 'bg-blue-500',
  qianwen: 'bg-purple-500',
  wenxin: 'bg-red-500',
  google: 'bg-sky-500',
  mistral: 'bg-amber-500',
  xai: 'bg-slate-600',
  groq: 'bg-violet-500',
  moonshot: 'bg-indigo-500',
  zhipu: 'bg-cyan-500',
  doubao: 'bg-teal-500',
  yi: 'bg-fuchsia-500',
  custom: 'bg-gray-400',
}

export const PROVIDER_NAMES: Record<string, string> = {
  openai: 'OpenAI',
  anthropic: 'Anthropic',
  deepseek: 'DeepSeek',
  qianwen: '通义千问',
  wenxin: '文心一言',
  google: 'Google Gemini',
  mistral: 'Mistral',
  xai: 'xAI Grok',
  groq: 'Groq',
  moonshot: 'Moonshot (Kimi)',
  zhipu: '智谱 GLM',
  doubao: '字节豆包',
  yi: '零一万物 Yi',
  custom: '自定义',
}
